image: Visual Studio 2022

before_build:
  - dotnet restore

build_script:
  - dotnet build -c "Debug" --no-restore
  - dotnet pack ./src/Otp.NET/Otp.NET.csproj --no-build -o ./dist  -c "Debug"

test_script:
  - dotnet test --no-build

deploy: off

artifacts:
  - path: 'dist\*.nupkg'
